# Generated by Django 5.2.8 on 2025-11-23 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product title', max_length=200)),
                ('description', models.TextField(help_text='Product description')),
                ('image', models.ImageField(help_text='Product image', upload_to='products/')),
                ('slug', models.SlugField(help_text='URL-friendly version of title (auto-generated)', unique=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this product')),
                ('category', models.CharField(blank=True, help_text='Product category', max_length=100)),
                ('material', models.CharField(blank=True, help_text='e.g., 100% Recyclable Kraft Paper', max_length=200)),
                ('gsm_range', models.CharField(blank=True, help_text='e.g., 100-300 GSM', max_length=100)),
                ('handle_type', models.CharField(blank=True, help_text='e.g., Twisted/Flat handles available', max_length=200)),
                ('customization', models.CharField(blank=True, help_text='e.g., Custom sizes and printing', max_length=200)),
                ('feature_1', models.CharField(blank=True, max_length=200)),
                ('feature_2', models.CharField(blank=True, max_length=200)),
                ('feature_3', models.CharField(blank=True, max_length=200)),
                ('feature_4', models.CharField(blank=True, max_length=200)),
                ('feature_5', models.CharField(blank=True, max_length=200)),
                ('feature_6', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Menu item title', max_length=100)),
                ('url', models.CharField(blank=True, help_text='URL path (e.g., /about/ or leave blank for dropdown parent)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this menu item')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('parent', models.ForeignKey(blank=True, help_text='Leave blank for top-level menu item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order', 'title'],
            },
        ),
    ]
