# Generated by Django 5.2.8 on 2025-11-23 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name', max_length=200)),
                ('company_name', models.CharField(blank=True, help_text='Company name (optional)', max_length=200)),
                ('email', models.EmailField(help_text='Customer email', max_length=254)),
                ('contact_number', models.CharField(help_text='Contact phone number', max_length=20)),
                ('size', models.CharField(help_text='Required size (e.g., 10x12x5 inches)', max_length=100)),
                ('gsm', models.CharField(help_text='GSM specification (e.g., 120 GSM)', max_length=50)),
                ('quantity', models.IntegerField(help_text='Quantity needed')),
                ('message', models.TextField(blank=True, help_text='Additional requirements or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Mark as processed')),
                ('product', models.ForeignKey(help_text='Product of interest', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
