# Generated by Django 5.2.8 on 2025-12-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question', max_length=300)),
                ('answer', models.TextField(help_text='The answer (supports HTML)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('category', models.CharField(blank=True, help_text='Optional category for grouping FAQs', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Show on FAQ page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
