# Generated by Django 5.2.8 on 2025-12-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Industry name (e.g., Restaurant & Takeout)', max_length=200)),
                ('image', models.ImageField(help_text='Industry icon/image', upload_to='industries/')),
                ('url', models.CharField(help_text='URL path (e.g., /restaurant-paper-bags/)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this industry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['order', 'title'],
            },
        ),
    ]
