# Generated by Django 5.2.8 on 2025-12-14 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Category name (e.g., Brown Kraft Bags)', max_length=200)),
                ('description', models.TextField(help_text='Category description (e.g., Grocery & Food Packaging)')),
                ('image', models.ImageField(help_text='Category image', upload_to='product-categories/')),
                ('slug', models.SlugField(help_text='URL-friendly version of title (auto-generated)', unique=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this category')),
                ('material', models.CharField(blank=True, help_text='e.g., 100% Recyclable Kraft Paper', max_length=200)),
                ('gsm_range', models.CharField(blank=True, help_text='e.g., 100-300 GSM', max_length=100)),
                ('handle_type', models.CharField(blank=True, help_text='e.g., Twisted/Flat handles available', max_length=200)),
                ('customization', models.CharField(blank=True, help_text='e.g., Custom sizes and printing', max_length=200)),
                ('feature_1', models.CharField(blank=True, max_length=200)),
                ('feature_2', models.CharField(blank=True, max_length=200)),
                ('feature_3', models.CharField(blank=True, max_length=200)),
                ('feature_4', models.CharField(blank=True, max_length=200)),
                ('feature_5', models.CharField(blank=True, max_length=200)),
                ('feature_6', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Product (Deprecated)', 'verbose_name_plural': 'Products (Deprecated)'},
        ),
        migrations.AlterField(
            model_name='quote',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product of interest (deprecated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
        migrations.AddField(
            model_name='quote',
            name='product_category',
            field=models.ForeignKey(blank=True, help_text='Product category of interest', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
    ]
