# Generated by Django 5.2.8 on 2025-12-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productcategory_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Category description (e.g., Grocery & Food Packaging)'),
        ),
    ]
