# Generated by Django 5.2.8 on 2025-12-14 20:15

import django.db.models.deletion
from django.db import migrations, models


def migrate_quote_products(apps, schema_editor):
    """Copy existing product references to product_old field"""
    Quote = apps.get_model('core', 'Quote')
    for quote in Quote.objects.all():
        if quote.product_id:
            quote.product_old_id = quote.product_id
            quote.product_id = None
            quote.save(update_fields=['product_old_id', 'product_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='product_old',
            field=models.ForeignKey(blank=True, help_text='Old product model (deprecated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productold'),
        ),
        migrations.RunPython(migrate_quote_products, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product name (e.g., 10x12x5 Brown Kraft Bag)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Product description (optional)')),
                ('image', models.ImageField(help_text='Product image', upload_to='products/')),
                ('slug', models.SlugField(help_text='URL-friendly version of title (auto-generated)', unique=True)),
                ('size', models.CharField(blank=True, help_text='e.g., 10x12x5 inches', max_length=100)),
                ('gsm', models.CharField(blank=True, help_text='e.g., 120 GSM', max_length=50)),
                ('color', models.CharField(blank=True, help_text='e.g., Brown, White, Custom', max_length=100)),
                ('handle_type', models.CharField(blank=True, help_text='e.g., Twisted, Flat, No Handle', max_length=200)),
                ('price_range', models.CharField(blank=True, help_text='e.g., $0.50 - $1.00 per piece', max_length=100)),
                ('minimum_order', models.IntegerField(blank=True, help_text='Minimum order quantity', null=True)),
                ('feature_1', models.CharField(blank=True, help_text='Product feature', max_length=200)),
                ('feature_2', models.CharField(blank=True, help_text='Product feature', max_length=200)),
                ('feature_3', models.CharField(blank=True, help_text='Product feature', max_length=200)),
                ('feature_4', models.CharField(blank=True, help_text='Product feature', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order within category (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this product')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['category__order', 'order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='quote',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Specific product of interest', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
    ]
