# Generated by Django 5.2.8 on 2025-12-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='product_old',
        ),
        migrations.DeleteModel(
            name='ProductOld',
        ),
    ]
