# Generated by Django 5.2.8 on 2025-12-25 20:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cart_order_product_allow_backorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if different from default'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_5',
            field=models.CharField(blank=True, help_text='Product feature', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_6',
            field=models.CharField(blank=True, help_text='Product feature', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 70 chars)', max_length=70),
        ),
        migrations.AddField(
            model_name='product',
            name='schema_type',
            field=models.CharField(default='Product', help_text='Schema.org type', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='Internal search keywords (comma-separated)'),
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('volume', 'Volume Discount'), ('customer_group', 'Customer Group'), ('promo_code', 'Promo Code')], max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promo_code', models.CharField(blank=True, help_text='Required for promo code type', max_length=50)),
                ('min_quantity', models.IntegerField(blank=True, help_text='Minimum quantity for volume discount', null=True)),
                ('customer_group', models.CharField(blank=True, help_text="e.g., 'wholesale', 'vip'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, help_text='Leave blank for store-wide discount', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='core.product')),
            ],
            options={
                'verbose_name': 'Discount Rule',
                'verbose_name_plural': 'Discount Rules',
                'ordering': ['product', 'discount_type'],
            },
        ),
        migrations.CreateModel(
            name='ProductIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_products', to='core.industry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_industries', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Industry',
                'verbose_name_plural': 'Product Industries',
                'unique_together': {('product', 'industry')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='industries',
            field=models.ManyToManyField(blank=True, help_text='Industries this product serves', related_name='products_direct', through='core.ProductIndustry', to='core.industry'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('review', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Optional review image', null=True, upload_to='review-images/')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified purchase')),
                ('is_approved', models.BooleanField(default=False, help_text='Approved to display')),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('size', 'Size'), ('color', 'Color')], max_length=20)),
                ('name', models.CharField(help_text="e.g., 'Small', 'Red', '10x12x5'", max_length=100)),
                ('value', models.CharField(help_text='Display value', max_length=100)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price adjustment (+/-) from base price', max_digits=10)),
                ('sku_suffix', models.CharField(blank=True, help_text='SKU suffix for this variant', max_length=50)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Stock for this variant')),
                ('image', models.ImageField(blank=True, help_text='Variant-specific image (optional)', null=True, upload_to='product-variants/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product', 'variant_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TieredPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField(help_text='Minimum quantity for this tier')),
                ('max_quantity', models.IntegerField(blank=True, help_text='Maximum quantity (leave blank for unlimited)', null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label', models.CharField(blank=True, help_text="e.g., 'Bulk', 'Wholesale'", max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiered_prices', to='core.product')),
            ],
            options={
                'verbose_name': 'Tiered Pricing',
                'verbose_name_plural': 'Tiered Pricing',
                'ordering': ['product', 'min_quantity'],
            },
        ),
    ]
