# Generated by Django 5.2.8 on 2025-12-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_canonical_url_product_feature_5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_payments_enabled', models.BooleanField(default=False, help_text='Enable/disable Stripe online payments. When disabled, orders will be placed without payment.')),
                ('store_name', models.CharField(default='PackAxis Packaging Canada', max_length=100)),
                ('store_email', models.EmailField(default='hello@packaxis.ca', max_length=254)),
                ('store_phone', models.CharField(default='(647) 555-0123', max_length=20)),
                ('store_address', models.TextField(blank=True, default='Toronto, Ontario, Canada')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=13.0, help_text='Tax rate percentage (e.g., 13 for 13% HST)', max_digits=5)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount (0 = no minimum)', max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=500, help_text='Order amount for free shipping', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
