# Generated by Django 5.2.8 on 2025-12-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_user_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_eta',
            field=models.CharField(blank=True, help_text='Estimated delivery window', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, help_text='Selected shipping method', max_length=50),
        ),
    ]
