# Generated by Django 5.2.8 on 2025-12-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_shipping_eta_order_shipping_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique promo code (will be stored uppercase)', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='Internal description', max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('free_shipping', 'Free Shipping')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Percentage or fixed amount', max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order subtotal required', max_digits=10)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on discount amount (for percentage codes)', max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total times this code can be used (blank = unlimited)', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Times this code has been used')),
                ('per_user_limit', models.PositiveIntegerField(default=1, help_text='Times each user/email can use this code')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, help_text='Start date (blank = immediately)', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='End date (blank = never expires)', null=True)),
                ('first_order_only', models.BooleanField(default=False, help_text='Only valid for first-time customers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, help_text='Applied promo code', max_length=50),
        ),
    ]
