# Generated by Django 5.2.8 on 2025-12-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_step',
            field=models.IntegerField(choices=[(1, 'Order Placed'), (2, 'Processing'), (3, 'Shipped'), (4, 'Delivered')], default=1, help_text='Current tracking step (1-4)'),
        ),
    ]
