# Generated by Django 5.2.8 on 2026-01-01 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_tracking_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Restaurants & Cafes', max_length=100, unique=True)),
                ('description', models.TextField(help_text='e.g., Perfect for takeout orders, delivery bags, and branded customer packaging.')),
                ('icon_name', models.CharField(choices=[('users', 'Users/People'), ('home', 'Home/Retail'), ('box', 'E-commerce/Shipping'), ('gift', 'Corporate Gifts'), ('shopping-bag', 'Shopping Bag'), ('coffee', 'Cafe/Restaurant'), ('store', 'Store/Shop'), ('truck', 'Delivery/Logistics')], default='users', help_text='Icon for this use case', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order in the global list')),
                ('is_active', models.BooleanField(default=True, help_text='Make this use case available for products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Use Case',
                'verbose_name_plural': 'Use Cases',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='productreview',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order this review is linked to (for verification)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified purchase (auto-set if linked to order)'),
        ),
        migrations.CreateModel(
            name='ProductUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable this use case for this product')),
                ('order', models.IntegerField(default=0, help_text='Display order for this product (overrides global order)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_use_cases', to='core.product')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_case_products', to='core.usecase')),
            ],
            options={
                'verbose_name': 'Product Use Case',
                'verbose_name_plural': 'Product Use Cases',
                'ordering': ['order', 'use_case__order'],
                'unique_together': {('product', 'use_case')},
            },
        ),
    ]
