# Generated by Django 5.2.8 on 2026-01-02 05:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_usecase_productreview_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image (optional)', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Specific product of interest', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('volume', 'Volume Discount'), ('customer_group', 'Customer Group'), ('promo_code', 'Promo Code')], max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promo_code', models.CharField(blank=True, help_text='Required for promo code type', max_length=50)),
                ('min_quantity', models.IntegerField(blank=True, help_text='Minimum quantity for volume discount', null=True)),
                ('customer_group', models.CharField(blank=True, help_text="e.g., 'wholesale', 'vip'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, help_text='Leave blank for store-wide discount', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='core.product')),
            ],
            options={
                'verbose_name': 'Discount Rule',
                'verbose_name_plural': 'Discount Rules',
                'ordering': ['product', 'discount_type'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('size', 'Size'), ('color', 'Color')], max_length=20)),
                ('name', models.CharField(help_text="e.g., 'Small', 'Red', '10x12x5'", max_length=100)),
                ('value', models.CharField(help_text='Display value', max_length=100)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price adjustment (+/-) from base price', max_digits=10)),
                ('sku_suffix', models.CharField(blank=True, help_text='SKU suffix for this variant', max_length=50)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Stock for this variant')),
                ('image', models.ImageField(blank=True, help_text='Variant-specific image (optional)', null=True, upload_to='product-variants/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product', 'variant_type', 'order'],
            },
        ),
    ]
