# Generated by Django 5.2.8 on 2026-01-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_product_image_alter_quote_product_discountrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image (optional)', null=True, upload_to='product-categories/'),
        ),
    ]
