# Generated by Django 5.2.8 on 2026-01-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_productcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name (e.g., Eco-Friendly, Bulk Discount, Custom Print)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of name', unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Tag color in hex format (e.g., #3B82F6)', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Optional description for this tag')),
                ('order', models.IntegerField(default=0, help_text='Display order for tag lists')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Product Tags',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='industry',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent industry for nested sub-industries', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.industry'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category for nested sub-categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.productcategory'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of title (auto-generated)'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('slug', 'parent')},
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['is_active', 'order'], name='core_indust_is_acti_62ec74_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['parent'], name='core_indust_parent__651c13_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent'], name='core_produc_parent__cdb9e5_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='core_tag_slug_4ab57c_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_active', 'order'], name='core_tag_is_acti_4b5aec_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Product tags for filtering and organization', related_name='products', to='core.tag'),
        ),
    ]
