# Generated by Django 5.2.8 on 2026-01-02 18:59

from django.db import migrations, models


def migrate_category_to_categories(apps, schema_editor):
    """Copy existing category FK data to new categories M2M field"""
    Product = apps.get_model('core', 'Product')
    
    for product in Product.objects.all():
        if hasattr(product, 'category') and product.category:
            # Add the existing category to the new categories field
            product.categories.add(product.category)
    
    print(f"✅ Migrated {Product.objects.count()} products to new categories field")


def reverse_migration(apps, schema_editor):
    """Reverse migration: set first category as the single category"""
    Product = apps.get_model('core', 'Product')
    
    for product in Product.objects.all():
        first_cat = product.categories.first()
        if first_cat:
            product.category = first_cat
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_hierarchical_categories_and_tags'),
    ]

    operations = [
        # Step 1: Add the new categories M2M field (nullable temporarily)
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(
                help_text='Product categories (can select multiple)', 
                related_name='products', 
                to='core.productcategory',
                blank=True
            ),
        ),
        
        # Step 2: Migrate data from old category field to new categories field
        migrations.RunPython(migrate_category_to_categories, reverse_migration),
        
        # Step 3: Remove the old category ForeignKey field
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        
        # Step 4: Remove the old index that referenced category
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_categor_9c2292_idx',
        ),
        
        # Step 5: Update model options (ordering changed)
        migrations.AlterModelOptions(
            name='product',
            options={
                'ordering': ['order', 'title'], 
                'verbose_name': 'Product', 
                'verbose_name_plural': 'Products'
            },
        ),
    ]
